version: '3'
services:
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:3.1.0
    container_name: xxl-admin
    ports:
      - "9999:8080"
    environment:
      PARAMS: >
        --spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
        --spring.datasource.username=root
        --spring.datasource.password=root
        --xxl.job.accessToken=default_token
    extra_hosts:
      - "host.docker.internal:172.22.84.232"  # 映射宿主机 IP
    networks:
      - tiktok_e-commence_app-network
    restart: unless-stopped

networks:
  tiktok_e-commence_app-network:
    external: true  # 使用现有的 app-network