version: '3'
services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db/sql/ini:/docker-entrypoint-initdb.d
  redis:
    image: redis:latest
    ports:
      - "6378:6378" # 主机端口:容器端口
    networks:
      - app-network
    command: redis-server --port 6378 # 确保容器内 Redis 使用 6378 端口
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6378", "ping"]
      interval: 10s
      retries: 3

volumes:
  mysql-data:
  redis-data:

networks:
  app-network:
    driver: bridge
