// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	cart "tiktok_e-commerce/api/biz/router/cart"
	payment "tiktok_e-commerce/api/biz/router/payment"
	product "tiktok_e-commerce/api/biz/router/product"
	user "tiktok_e-commerce/api/biz/router/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	cart.Register(r)

	product.Register(r)

	payment.Register(r)

	user.Register(r)
}
