 CREATE DATABASE IF NOT EXISTS `cartdb`  
    DEFAULT CHARACTER SET = 'utf8mb4';;

CREATE DATABASE IF NOT EXISTS `checkoutdb`
    DEFAULT CHARACTER SET = 'utf8mb4';

CREATE DATABASE IF NOT EXISTS `orderdb`
    DEFAULT CHARACTER SET = 'utf8mb4';

CREATE DATABASE IF NOT EXISTS `paymentdb`
    DEFAULT CHARACTER SET = 'utf8mb4';

CREATE DATABASE IF NOT EXISTS `productdb`
    DEFAULT CHARACTER SET = 'utf8mb4';

CREATE DATABASE IF NOT EXISTS `userdb`
    DEFAULT CHARACTER SET = 'utf8mb4';